/**
* Claptrap
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.claptrap.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 * @param id 
 * @param email 
 * @param name 
 * @param profilePictureUrl 
 */

data class UserWire (
    @field:JsonProperty("id")
    val id: kotlin.String,
    @field:JsonProperty("email")
    val email: kotlin.String,
    @field:JsonProperty("name")
    val name: kotlin.String? = null,
    @field:JsonProperty("profilePictureUrl")
    val profilePictureUrl: kotlin.String? = null
)

