openapi: 3.0.0
info:
  title: 'Claptrap'
  version: '1.0'

security:
  - bearerAuth: [ ]

paths:
  '/token-sign-in':
    put:
      operationId: tokenSignIn
      summary: |
        Validates the token, and initializes the user identified by the sub claim if the user
        is not already present inside the database. This token can come from either the Google,
        or the Firebase sign in provider.
      responses:
        '200':
          description: 'Validation successful. User was already present in the database.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DummyWire"
        '201':
          description: 'Validation successful. User was created.'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DummyWire"
        '401':
          description: 'Token validation failed. The token is either faulty or expired.'
  '/dummy':
    get:
      summary: 'Returns dummy data'
      responses:
        '201':
          description: 'Dummy data returned'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DummyWire'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    DummyWire:
      $ref: './schemas/DummyWire.yaml'
