package com.aradipatrik.claptrap.domain

enum class StatColor {
  STAT_COLOR_ONE,
  STAT_COLOR_TWO,
  STAT_COLOR_THREE,
  STAT_COLOR_FOUR,
  STAT_COLOR_FIVE,
  STAT_COLOR_SIX,
  STAT_COLOR_SEVEN,
  STAT_COLOR_EIGHT,
  STAT_COLOR_NINE,
  STAT_COLOR_TEN,
}