/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.claptrap.api;

import com.claptrap.model.DummyWire;
import io.swagger.annotations.*;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.GetMapping;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-05-01T18:46:15.460440100+02:00[Europe/Budapest]")
@Api(value = "dummy", description = "the dummy API")
public interface DummyApi {

  /**
   * GET /dummy : Returns dummy data
   *
   * @return Dummy data returned (status code 201)
   */
  @ApiOperation(value = "Returns dummy data", nickname = "dummyGet", notes = "", response = DummyWire.class, responseContainer = "List", authorizations = {

    @Authorization(value = "bearerAuth")
  }, tags = {})
  @ApiResponses(value = {
    @ApiResponse(code = 201, message = "Dummy data returned", response = DummyWire.class, responseContainer = "List")})
  @GetMapping(
    value = "/dummy",
    produces = {"application/json"}
  )
  Flux<DummyWire> dummyGet(@AuthenticationPrincipal Mono<Jwt> jwt);
}
